language: ruby
before_install:
  - gem install bundler
before_script:
  - bundle update
rvm:
  - 2.0.0
  - 2.1.8
  - 2.2.4
  - 2.3.0
  - ruby-head
gemfile:
  - gemfiles/rails3.gemfile
  - gemfiles/rails40.gemfile
  - gemfiles/rails41.gemfile
  - gemfiles/rails42.gemfile
notifications:
  emails:
    - tsukasa.oishi@gmail.com
