language: ruby
before_install:
  - gem install bundler
before_script:
  - bundle update
cache: bundler
rvm:
  - 2.1.10
  - 2.2.6
  - 2.3.3
  - 2.4.0
gemfile:
  - gemfiles/rails42.gemfile
  - gemfiles/rails50.gemfile
matrix:
  exclude:
    - rvm: 2.1.10
      gemfile: gemfiles/rails50.gemfile
  fast_finish: true
bundler_args: --jobs 3 --retry 3
