language: ruby
before_install:
  - gem install bundler
before_script:
  - bundle update
rvm:
  - 2.0.0
  - 2.1.8
  - 2.2.4
  - 2.3.0
  - ruby-head
notifications:
  emails:
    - tsukasa.oishi@gmail.com
